// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASFuWcxRfgmg_uWC6uSlmtIDRNf_7ApDU',
    appId: '1:103979123691:web:2f1a48af2251a7e7e48fae',
    messagingSenderId: '103979123691',
    projectId: 'fir-practice-69acf',
    authDomain: 'fir-practice-69acf.firebaseapp.com',
    storageBucket: 'fir-practice-69acf.appspot.com',
    measurementId: 'G-38Z439LPPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDokAKBIwbKFfWaS2I7zE4Pr-IWDtR0FDY',
    appId: '1:103979123691:android:e3be91d7907033d7e48fae',
    messagingSenderId: '103979123691',
    projectId: 'fir-practice-69acf',
    storageBucket: 'fir-practice-69acf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMKIoGf9mPSji1zYRew1mlg072s2nJgls',
    appId: '1:103979123691:ios:1c8b26dca758d0b5e48fae',
    messagingSenderId: '103979123691',
    projectId: 'fir-practice-69acf',
    storageBucket: 'fir-practice-69acf.appspot.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMKIoGf9mPSji1zYRew1mlg072s2nJgls',
    appId: '1:103979123691:ios:1c8b26dca758d0b5e48fae',
    messagingSenderId: '103979123691',
    projectId: 'fir-practice-69acf',
    storageBucket: 'fir-practice-69acf.appspot.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASFuWcxRfgmg_uWC6uSlmtIDRNf_7ApDU',
    appId: '1:103979123691:web:c402e03566fe09fae48fae',
    messagingSenderId: '103979123691',
    projectId: 'fir-practice-69acf',
    authDomain: 'fir-practice-69acf.firebaseapp.com',
    storageBucket: 'fir-practice-69acf.appspot.com',
    measurementId: 'G-0R2PCHT5VX',
  );
}
